Basics

In [1]:
import numpy as np

In [17]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get dimensions
b.ndim

2

In [9]:
b.shape

(2, 3)

In [14]:
a.dtype

dtype('int16')

In [18]:
a.itemsize

4

In [19]:
a.nbytes

12

Changing specific elements

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [8]:
print(a[1,-2])

13


In [9]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
a[:,2]

array([ 3, 10])

In [11]:
a[0,1:6:2]

array([2, 4, 6])

Different Types of Arrays

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [15]:
np.full((3,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [17]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
np.random.rand(4,5)

array([[0.73566603, 0.78101385, 0.05837545, 0.77660066, 0.33723507],
       [0.73086872, 0.99205912, 0.44645838, 0.20778753, 0.37088183],
       [0.47505199, 0.89496266, 0.34977731, 0.01076744, 0.75563323],
       [0.42191784, 0.03009651, 0.73994147, 0.28682972, 0.96372395]])

In [29]:
np.random.randint(low=10, high=100, size=(4,5))

array([[77, 38, 14, 39, 28],
       [36, 76, 31, 92, 60],
       [77, 38, 60, 40, 41],
       [85, 61, 83, 52, 37]], dtype=int32)

In [30]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
a = np.array([[1,2,3]])
b = np.repeat(a,3,axis=0)
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = np.zeros((3,3))
arr[2,2] = 9

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### BE CAREFUL WHILE COPYING ARRAYS !!!!

In [ ]:
#### Warning #####
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [12]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


Mathematics

In [13]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
a + 2

array([3, 4, 5, 6])

In [15]:
a - 2

array([-1,  0,  1,  2])

In [16]:
a * 2

array([2, 4, 6, 8])

In [17]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [18]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [19]:
a ** 2

array([ 1,  4,  9, 16])

In [20]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

###### LINEAR ALGEBRA !!!

In [23]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [4]:
a = np.identity(3)
np.linalg.det(a)

np.float64(1.0)

###### # For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)
###### # # For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...


### Statistics

In [5]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(np.min(stats))
print(np.max(stats))
print(np.min(stats, axis = 0))
print(np.max(stats, axis = 0))
print(np.min(stats, axis = 1))
print(np.max(stats, axis = 1))

1
6
[1 2 3]
[4 5 6]
[1 4]
[3 6]


In [ ]:
np.sum(stats)
## axis = 0, over all the rows in a column
## axis = 1, over all the columns in a row

np.int64(21)

## Reorganizing arrays

In [21]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((2,2, 2))
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
h1 = np.zeros((2,4))
h2 = np.ones((2,5))

np.hstack((h1,h2))

array([[0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1.]])

##### Miscllaneous

1. Load Data from File

In [35]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [31]:
print(filedata > 50)
print(filedata[filedata > 50])

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196  75 766  75  55 999  78  76  88]


In [33]:
# You can index with list in NumPY
a = np.array([1,2,3,4,5,6,7,8])
a[[1,3,4]]

array([2, 4, 5])

In [38]:
print(np.any(filedata > 50, axis=0))
print(np.all(filedata > 50, axis=1))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False]


In [40]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [41]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
print(arr[2:4,0:2])
print(arr[[0,1,2,3],[1,2,3,4]])
print(arr[[0,4,5],3:])


[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
